set(_CATKIN_CURRENT_PACKAGE "minitask1")
set(minitask1_VERSION "0.0.0")
set(minitask1_MAINTAINER "milisan <milisan@todo.todo>")
set(minitask1_PACKAGE_FORMAT "2")
set(minitask1_BUILD_DEPENDS "geometry_msgs" "rospy" "std_msgs")
set(minitask1_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy" "std_msgs")
set(minitask1_BUILDTOOL_DEPENDS "catkin")
set(minitask1_BUILDTOOL_EXPORT_DEPENDS )
set(minitask1_EXEC_DEPENDS "geometry_msgs" "rospy" "std_msgs")
set(minitask1_RUN_DEPENDS "geometry_msgs" "rospy" "std_msgs")
set(minitask1_TEST_DEPENDS )
set(minitask1_DOC_DEPENDS )
set(minitask1_URL_WEBSITE "")
set(minitask1_URL_BUGTRACKER "")
set(minitask1_URL_REPOSITORY "")
set(minitask1_DEPRECATED "")